[package]
name = "genegraph-storage"
version = "0.12.0"
edition = "2024"
description = "vector database: base Lance storage"
authors = ["Lorenzo <tunedconsulting@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/tuned-org-uk/genegraph-storage"
homepage = "https://github.com/tuned-org-uk/genegraph-storage"
documentation = "https://docs.rs/genegraph-storage"
readme = "README.md"
keywords = ["graph-storage", "vector-space", "similarity-search", "mlops", "aiops"]
categories = ["filesystem", "database", "asynchronous", "algorithms", "database-implementations"]
exclude = [
    "target/*",
    "Cargo.lock",
    ".git/*",
    ".github/*",
    "*.tmp",
    "docs/*",
    "becnhes/*",
    "examples/*"

]

[dependencies]
smartcore = {version = "=0.5.0"}
ordered-float = "5.1.0"
rayon = "1.11.0"
sprs = "0.11.4"
log = "0.4.29"
env_logger = "0.11.9"
chrono = "0.4.42"
lance = { version = "6.0.0", default-features = false }
serde = { version = "^1.0.228", features = ["derive"] }
serde_json = { version = "^1.0.149"}
arrow = { version = "^59.0.0" }
uuid = { version = "1.21.0", features = ["v4", "serde"] }
futures = "0.3.32"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
parquet = { version = "^58.0.0" }

[dev-dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
approx = "0.5.1"
